## Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import os
import shutil
import openpyxl
from openpyxl.utils import get_column_letter
from openpyxl import load_workbook
from openpyxl.chart import BarChart, Reference, LineChart, PieChart
from openpyxl.chart.label import DataLabelList
from openpyxl.chart.series import SeriesLabel
from openpyxl.styles import Alignment  
from openpyxl.styles import PatternFill, Font
import xlwings as xw
from datetime import datetime
from contextlib import contextmanager

## Writer

In [2]:
@contextmanager
def excel_writer(file):
    writer = pd.ExcelWriter(
        file,
        engine="openpyxl",
        mode="a",
        if_sheet_exists="overlay",
        engine_kwargs={"keep_vba": True}
    )
    try:
        yield writer
    finally:
        writer.close()

## Functions

In [3]:
def autosize_df_columns(ws, df, start_col=1):
    for i, col in enumerate(df.columns, start=start_col):
        max_length = len(str(col))
        for val in df[col]:
            if val is not None:
                max_length = max(max_length, len(str(val)))
        ws.column_dimensions[get_column_letter(i)].width = max_length + 2

In [4]:
# Excel Generation function
def generate_excel(destination, excel_sheet_name, df, header_row):
    book = load_workbook(destination, keep_vba=True)
    with excel_writer(destination) as writer:
        sheet = excel_sheet_name
        df.to_excel(writer, sheet_name=sheet, index=False)
        ws = writer.sheets[sheet]

        header_row = header_row
        first_data_row = header_row + 1
        last_data_row = ws.max_row
        start_col = 1
        last_col = df.shape[1]

        ws.auto_filter.ref = f"{get_column_letter(start_col)}{header_row}:{get_column_letter(last_col)}{last_data_row}"

        wb = writer.book
        ws = wb[sheet]
        autosize_df_columns(ws, df)

In [5]:
# delete sheet in excel sheet function
def delete_excel_sheet(destination, excel_sheet_name):
    wb = load_workbook(destination, keep_vba=True)
    if excel_sheet_name in wb.sheetnames:
        del wb[excel_sheet_name]
    wb.save(destination)

In [6]:
# Apply color to the different groups for differentiation
def apply_group_colors(destination, sheet_name):
    wb = load_workbook(destination, keep_vba=True)
    ws = wb[sheet_name]
    colors = [
        PatternFill(start_color="FFCCCC", end_color="FFCCCC", fill_type="solid"),
        PatternFill(start_color="CCE5FF", end_color="CCE5FF", fill_type="solid"),
        PatternFill(start_color="E2EFDA", end_color="E2EFDA", fill_type="solid"),
        PatternFill(start_color="FFF2CC", end_color="FFF2CC", fill_type="solid")
    ]
    last_group = None
    color_idx = -1
    for row_num in range(2, ws.max_row + 1):
        current_group = ws.cell(row=row_num, column=4).value
        
        if current_group != last_group:
            color_idx = (color_idx + 1) % len(colors)
            
        for col_num in range(1, ws.max_column + 1):
            ws.cell(row=row_num, column=col_num).fill = colors[color_idx]
            
        last_group = current_group
    wb.save(destination)

In [7]:
# Excel Clickable Link function (for clicking and changing to the relevant sheet)
def excel_clickable_cell(val, sheet, cell="A1"):
    if val is None or str(val).strip() == "":
        return val
    return f'=HYPERLINK("#\'{sheet}\'!{cell}", "{val}")'

In [8]:
# Chart functions
def merge_cells_title(sheet, cell1, cell2, row_no, col, val, horizontal_val, vertical_val, color):
    sheet.merge_cells(f'{cell1}:{cell2}')
    cell = sheet.cell(row=row_no, column=col)
    cell.value = val
    cell.alignment = Alignment(horizontal=horizontal_val, vertical=vertical_val)
    cell.fill = PatternFill(start_color=color, end_color=color, fill_type="solid")

In [9]:
def hyperlink_cell(ws, first_data_row, last_data_row, column_no=1):
    for row in range(first_data_row, last_data_row + 1):
        ws.cell(row=row, column=column_no).style = "Hyperlink"

In [10]:
def univariate_table(df, variable, top_n=5):
    counts = df[variable].value_counts().reset_index()
    counts.columns = [variable, 'count']
    if variable == 'severity':
        severity_order = ['Critical', 'High', 'Medium', 'Low']
        counts[variable] = pd.Categorical(counts[variable], categories=severity_order, ordered=True)
        counts = counts.sort_values(by=variable)
    if len(counts) > top_n:
        sub_df = counts.head(top_n).copy()
        misc_count = counts.iloc[top_n:]['count'].sum()
        misc_row = pd.DataFrame({variable: ['Misc'], 'count': [misc_count]})
        sub_df = pd.concat([sub_df, misc_row], ignore_index=True)
    else:
        sub_df = counts
    sub_df_rows = sub_df.shape[0]
    sub_df_columns = sub_df.shape[1]
    return sub_df, sub_df_rows, sub_df_columns

In [11]:
def pivot_table(df, index_col, col, val):
    pivot_table_df = pd.pivot_table(df, index=index_col, columns=col, values=val, aggfunc="count", fill_value=0).stack().reset_index()
    if isinstance(index_col, list):
        new_cols = index_col + [col, "count"]
    else:
        new_cols = [index_col, col, "count"]
    pivot_table_df.columns = new_cols
    return pivot_table_df

In [12]:
def pivot_table_wide(df, index_col, col, val, sheet=None, cell=None):
    column_order = ["Critical", "High", "Medium", "Low"]
    pivot_df = pivot_table(df, index_col, col, val)
    pivot_df_wide = (
        pivot_df
        .pivot(index=index_col, columns=col, values="count")
        .fillna(0)
    )
    existing_cols = [c for c in column_order if c in pivot_df_wide.columns]
    pivot_df_wide = pivot_df_wide.reindex(columns=existing_cols)
    pivot_df_wide = pivot_df_wide.reset_index()
    if isinstance(index_col, list):
        pivot_df_wide.insert(2, 'Label',
                             pivot_df_wide[index_col[0]].astype(str).str.strip()
                             + " - " +
                             pivot_df_wide[index_col[1]].astype(str).str.strip()
                             )
    pivot_df_wide_rows = pivot_df_wide.shape[0]
    pivot_df_wide_columns = pivot_df_wide.shape[1]
    return pivot_df_wide, pivot_df_wide_rows, pivot_df_wide_columns

In [13]:
def barchart_creation(sheet, chartType, variable, x_title, y_title, min_col, max_col, min_row, max_row, showVal, showSerName, showCatName, showLeaderLines, cell, chartStyle=None, chartGrouping=None, chartOverlap=None, shape=None, header_row=None):
    chart = BarChart()
    chart.type = chartType
    if chartStyle is not None:
        chart.style = chartStyle
    if chartGrouping is not None:
        chart.grouping = chartGrouping
    if chartOverlap is not None:
        chart.overlap = chartOverlap
    chart.title = f"Vulnerabilities by {variable}"

    if header_row is None:
        header_row = min_row
    data_start_row = min_row + 1
    num_categories = max_row - data_start_row + 1

    chart.x_axis.title = x_title
    chart.y_axis.title = y_title
    chart.y_axis.majorGridlines = None
    chart.x_axis.title.overlay = False
    chart.y_axis.title.overlay = False
    chart.legend.overlay = False
    chart.title.overlay = False

    data = Reference(sheet, min_col=min_col, min_row=data_start_row, max_row=max_row, max_col=max_col)
    cats = Reference(sheet, min_col=min_col - 1, min_row=data_start_row, max_row=max_row)

    chart.add_data(data, titles_from_data=False)
    chart.set_categories(cats)

    for i, series in enumerate(chart.series):
        header_cell = sheet.cell(row=header_row, column=min_col + i)
        series.title = SeriesLabel(strRef=None, v=str(header_cell.value))

    chart.dataLabels = DataLabelList()
    chart.dataLabels.showVal = showVal
    chart.dataLabels.showSerName = showSerName
    chart.dataLabels.showCatName = showCatName
    chart.dataLabels.showLeaderLines = showLeaderLines

    if chartGrouping is not None:
        chart.x_axis.delete = False
        chart.x_axis.tickLblPos = "nextTo"
        chart.x_axis.crosses = "autoZero"
        chart.x_axis.tickLblSkip = 1
        chart.x_axis.tickMarkSkip = 1
    else:
        chart.x_axis.tickLblPos = "low"
        chart.x_axis.crosses = "min"
        chart.x_axis.tickLblSkip = 1
        chart.x_axis.tickMarkSkip = 1

    chart.width = 6 + (num_categories * 2)
    chart.height = 7 + (num_categories * 0.1)

    sheet.add_chart(chart, cell)
    return chart

In [14]:
def batch_barchart(sheet, batch_size=5, **kwargs):
    header_row = kwargs["min_row"]
    max_row = kwargs["max_row"]
    first_data_row = header_row + 1
    num_categories = max_row - header_row

    if num_categories <= batch_size:
        return [barchart_creation(sheet=sheet, header_row=header_row, **kwargs)]

    start_col = kwargs["max_col"] + 3
    charts = []
    batch_index = 0

    for start in range(first_data_row, max_row + 1, batch_size):
        end = min(start + batch_size - 1, max_row)
        cell_position = f"{get_column_letter(start_col)}{4 + batch_index * 20}"

        chart = barchart_creation(
            sheet=sheet,
            min_row=start - 1,      # header for this batch = row just above batch
            max_row=end,
            cell=cell_position,
            header_row=header_row,  # fixed original header row for legend names
            **{k: v for k, v in kwargs.items() if k not in ["min_row", "max_row", "cell"]}
        )

        charts.append(chart)
        batch_index += 1

    return charts

In [15]:
def piechart_creation(sheet, shape, variable, min_col, min_row, max_row, max_col, showVal, showSerName, showCatName, showPercent, cell):
    chart = PieChart()
    chart.title = f"Vulnerabilities by {variable}"
    num_categories = max_row - min_row

    # Data & Categories
    data = Reference(sheet, min_col=min_col, min_row=min_row, max_row=max_row, max_col=max_col)
    cats = Reference(sheet, min_col=min_col-1, min_row=min_row+1, max_row=max_row)
    chart.add_data(data, titles_from_data=True)
    chart.dataLabels = DataLabelList() 
    chart.dataLabels.showVal = showVal
    chart.dataLabels.showSerName = showSerName
    chart.dataLabels.showCatName = showCatName
    chart.dataLabels.showPercent = showPercent
    chart.set_categories(cats)

    chart.shape = shape
    chart.width = 6 + (num_categories * 2) 
    chart.height = 7 + (num_categories * 0.1)
    sheet.add_chart(chart, cell)
    return chart

## Main Function

### Data Manipulation

In [16]:
today = datetime.today()
new_file_name = "dummy_data"
raw_df = pd.read_excel(f"{new_file_name}_raw.xlsx")
df = raw_df.copy()

# insert 'scan' column defined based on the value in 'port'
target_position = df.columns.get_loc('port') + 1
target_values = np.where(df['port'] != 0, 'Network Scan', 'Agent Scan')
df.insert(loc=target_position, column='scan', value=target_values)

df.head()

,plugin_id,plugin_family,severity,asset_group,port,scan,patch_publication_date,first_observed_date,last_observed_date
0,1993,Windows,Medium,App Servers,0,Agent Scan,2025-11-01,2025-12-01,2026-02-08 18:29:19
1,1656,Windows,High,Infra,443,Network Scan,2025-11-02,2025-12-02,2026-01-22 03:41:11
2,1275,Database,High,Web Servers,443,Network Scan,2025-11-03,2025-12-03,2026-02-08 13:05:39
3,1529,Network,Critical,Infra,0,Agent Scan,2025-11-04,2025-12-04,2026-01-18 07:24:03
4,1399,Windows,High,DB Servers,0,Agent Scan,2025-11-05,2025-12-05,2026-01-14 06:01:51

In [17]:
# copy the template excel file into a new file
newfile = f"{new_file_name}.xlsm"
if os.path.exists(newfile):
    os.remove(newfile)
source_file = "./template.xlsm"
shutil.copy(source_file, newfile)

'dummy_data.xlsm'

In [18]:
# calculate difference based on severity level
severity_thresholds = {"Critical": 60, "High": 60, "Medium": 90, "Low": 90}

# time columns conversion
df['patch_publication_date'] = pd.to_datetime(df['patch_publication_date'], format = "%d/%m/%Y %H:%M:%S")
df['first_observed_date'] = pd.to_datetime(df['first_observed_date'], format="%d/%m/%Y %H:%M:%S")
df['last_observed_date'] = pd.to_datetime(df['last_observed_date'], format="%d/%m/%Y %H:%M:%S")
df['Days Discovered (Days)'] = (df['last_observed_date'] - df['first_observed_date']).dt.days

# create a new column for today's date
df['comparison_date'] = pd.to_datetime(today, format="%d/%m/%Y %H:%M:%S")

# create a new column to calculate the difference in days
for idx, row in df.iterrows():
    if pd.isnull(row['patch_publication_date']):
        df.at[idx, "difference"] = (row['comparison_date'] - row['first_observed_date']).days
    else:
        df.at[idx, "difference"] = (row['comparison_date'] - row['patch_publication_date']).days

# create a new column to apply the overdue flah (Y or N)
df["overdue"] = df.apply(
    lambda row: "Y" if row["difference"] > severity_thresholds[row["severity"]] else "N",
    axis=1
)

df = df.drop('comparison_date', axis=1)

df.head()

,plugin_id,plugin_family,severity,asset_group,port,scan,patch_publication_date,first_observed_date,last_observed_date,Days Discovered (Days),difference,overdue
0,1993,Windows,Medium,App Servers,0,Agent Scan,2025-11-01,2025-12-01,2026-02-08 18:29:19,69,165.0,Y
1,1656,Windows,High,Infra,443,Network Scan,2025-11-02,2025-12-02,2026-01-22 03:41:11,51,164.0,Y
2,1275,Database,High,Web Servers,443,Network Scan,2025-11-03,2025-12-03,2026-02-08 13:05:39,67,163.0,Y
3,1529,Network,Critical,Infra,0,Agent Scan,2025-11-04,2025-12-04,2026-01-18 07:24:03,45,162.0,Y
4,1399,Windows,High,DB Servers,0,Agent Scan,2025-11-05,2025-12-05,2026-01-14 06:01:51,40,161.0,Y

In [19]:
# seperate the df into individual df
overdue_df = df.loc[df['overdue'] == 'Y'].reset_index(drop=True)
non_overdue_df = df.loc[df['overdue'] == 'N'].reset_index(drop=True)

low_df = df.loc[df['severity']=='Low'].reset_index(drop=True)
medium_df = df.loc[df['severity']=='Medium'].reset_index(drop=True)
high_df = df.loc[df['severity']=='High'].reset_index(drop=True)
critical_df = df.loc[df['severity']=='Critical'].reset_index(drop=True)

In [20]:
overdue_df["Days Overdued By (Days)"] = overdue_df['difference'] - overdue_df['severity'].map(severity_thresholds)
non_overdue_df["Days to Overdue (Days)"] = non_overdue_df['severity'].map(severity_thresholds) - non_overdue_df['difference']
overdue_df = overdue_df.drop('difference', axis=1)
non_overdue_df = non_overdue_df.drop('difference', axis=1)

In [21]:
overdue_df.head()

,plugin_id,plugin_family,severity,asset_group,port,scan,patch_publication_date,first_observed_date,last_observed_date,Days Discovered (Days),overdue,Days Overdued By (Days)
0,1993,Windows,Medium,App Servers,0,Agent Scan,2025-11-01,2025-12-01,2026-02-08 18:29:19,69,Y,75.0
1,1656,Windows,High,Infra,443,Network Scan,2025-11-02,2025-12-02,2026-01-22 03:41:11,51,Y,104.0
2,1275,Database,High,Web Servers,443,Network Scan,2025-11-03,2025-12-03,2026-02-08 13:05:39,67,Y,103.0
3,1529,Network,Critical,Infra,0,Agent Scan,2025-11-04,2025-12-04,2026-01-18 07:24:03,45,Y,102.0
4,1399,Windows,High,DB Servers,0,Agent Scan,2025-11-05,2025-12-05,2026-01-14 06:01:51,40,Y,101.0

In [22]:
non_overdue_df.head()

,plugin_id,plugin_family,severity,asset_group,port,scan,patch_publication_date,first_observed_date,last_observed_date,Days Discovered (Days),overdue,Days to Overdue (Days)
0,1174,Linux,Medium,DB Servers,443,Network Scan,2026-01-16,2026-02-15,2026-03-24 20:35:54,37,N,1.0
1,1168,Database,Low,DB Servers,80,Network Scan,2026-01-19,2026-02-18,2026-01-31 15:56:58,-18,N,4.0
2,1302,Database,Low,App Servers,0,Agent Scan,2026-01-24,2026-02-23,2026-02-11 21:19:56,-12,N,9.0
3,1285,Network,Medium,Web Servers,443,Network Scan,2026-01-25,2026-02-24,2026-02-20 14:49:39,-4,N,10.0
4,1985,Windows,Medium,Web Servers,443,Network Scan,2026-01-26,2026-02-25,2026-03-11 09:07:42,14,N,11.0

In [23]:
raw_df = raw_df.sort_values(by=["asset_group", "plugin_family"]).reset_index(drop=True)
asset_group_rows = raw_df.index[raw_df["asset_group"].ne(raw_df["asset_group"].shift())]
# print(asset_group_rows)
asset_group_family_rows = raw_df.index[raw_df[["asset_group", "plugin_family"]].ne(raw_df[["asset_group", "plugin_family"]].shift()).any(axis=1)]
# print(asset_group_family_rows)
asset_group_dict = {raw_df.loc[idx, "asset_group"]: idx+2 for idx in asset_group_rows} # retrieve the rows that the new asset_group start at in the table for hyperlink later on, +2 because of pandas indexing and header row
# print(asset_group_dict)
asset_group_family_dict = {f"{raw_df.loc[idx, 'asset_group']} - {raw_df.loc[idx, 'plugin_family']}": idx+2 for idx in asset_group_family_rows}
# print(asset_group_family_dict)

In [24]:
# place this new table with additional columns into a new sheet
sheet_name = "Overdue Vulnerabilities"
generate_excel(newfile, sheet_name, overdue_df, 1)
sheet_name = "Non-Overdue Vulnerabilities"
generate_excel(newfile, sheet_name, non_overdue_df, 1)
sheet_name = "Original Vulnerabilities"
generate_excel(newfile, sheet_name, raw_df, 1)
apply_group_colors(newfile, sheet_name)
sheet_name = "Low Vulnerabilities"
generate_excel(newfile, sheet_name, low_df, 1)
sheet_name = "Medium Vulnerabilities"
generate_excel(newfile, sheet_name, medium_df, 1)
sheet_name = "High Vulnerabilities"
generate_excel(newfile, sheet_name, high_df, 1)
sheet_name = "Critical Vulnerabilities"
generate_excel(newfile, sheet_name, critical_df, 1)
delete_excel_sheet(newfile, "Sheet1")

In [25]:
family_vul, family_vul_rows, family_vul_columns = univariate_table(df, 'plugin_family')
severity_vul, severity_vul_rows, severity_vul_columns = univariate_table(df, 'severity')
severity_vul['severity'] = severity_vul['severity'].apply(lambda x: excel_clickable_cell(x, sheet=f"{x} Vulnerabilities"))
asset_group_vul, asset_group_vul_rows, asset_group_vul_columns = univariate_table(df, 'asset_group')
asset_group_vul['asset_group'] = asset_group_vul['asset_group'].apply(lambda x: excel_clickable_cell(x, sheet="Original Vulnerabilities", cell=f"A{asset_group_dict.get(x, 1)}"))
overdue_vul, overdue_vul_rows, overdue_vul_columns = univariate_table(df, 'overdue')
overdue_vul['overdue'] = np.where(overdue_vul['overdue'] == "Y", overdue_vul['overdue'].apply(excel_clickable_cell, sheet="Overdue Vulnerabilities"), overdue_vul['overdue'].apply(excel_clickable_cell, sheet="Non-Overdue Vulnerabilities"))
# barchart_start_column_value = family_vul_columns+2
# barchart_start_column = get_column_letter(barchart_start_column_value)
pivot_table_1_wide, pivot_table_1_wide_rows, pivot_table_1_wide_columns = pivot_table_wide(df, "plugin_family", "severity", "plugin_id")
pivot_table_2_wide, pivot_table_2_wide_rows, pivot_table_2_wide_columns = pivot_table_wide(df, "asset_group", "severity", "plugin_id")
pivot_table_2_wide['asset_group'] = pivot_table_2_wide['asset_group'].apply(lambda x: excel_clickable_cell(x, sheet="Original Vulnerabilities", cell=f"A{asset_group_dict.get(x, 1)}"))
pivot_table_3_wide, pivot_table_3_wide_rows, pivot_table_3_wide_columns = pivot_table_wide(df, "overdue", "severity", "plugin_id")
pivot_table_3_wide['overdue'] = np.where(pivot_table_3_wide['overdue'] == "Y", pivot_table_3_wide['overdue'].apply(excel_clickable_cell, sheet="Overdue Vulnerabilities"), pivot_table_3_wide['overdue'].apply(excel_clickable_cell, sheet="Non-Overdue Vulnerabilities"))
pivot_table_4_wide, pivot_table_4_wide_rows, pivot_table_4_wide_columns = pivot_table_wide(df, ["asset_group", "plugin_family"], "severity", "plugin_id")
pivot_table_4_wide['Label'] = pivot_table_4_wide['Label'].apply(lambda x: excel_clickable_cell(x, sheet="Original Vulnerabilities", cell=f"A{asset_group_family_dict.get(x, 1)}"))

In [26]:
asset_group_vul_rows

6

### Summary Sheet

In [27]:
sheet_name = "Summary"
book = load_workbook(newfile, keep_vba=True)
with excel_writer(newfile) as writer:
    sheet = sheet_name
    new_row = 3
    overdue_vul.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)
    ws = writer.sheets[sheet]
    header_row = new_row+1
    first_data_row = header_row+1
    last_data_row = header_row+overdue_vul_rows
    hyperlink_cell(ws, first_data_row, last_data_row)
    new_row = new_row + overdue_vul_rows + 2
    severity_vul.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)
    header_row = new_row+1
    first_data_row = header_row+1
    last_data_row = header_row+severity_vul_rows
    hyperlink_cell(ws, first_data_row, last_data_row)
    new_row = new_row + severity_vul_rows + 2
    asset_group_vul.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)
    header_row = new_row+1
    first_data_row = header_row+1
    last_data_row = header_row+asset_group_vul_rows
    hyperlink_cell(ws, first_data_row, last_data_row)
    new_row = new_row + asset_group_vul_rows + 2
    family_vul.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)

    wb = writer.book
    ws = wb[sheet]
    autosize_df_columns(ws, family_vul)
    wb.move_sheet(ws, offset=-wb.sheetnames.index(sheet))

wb = load_workbook(newfile, keep_vba=True)
sheet = wb[sheet_name]

charts_length = []

min_row_table = 4
max_row_table = min_row_table + overdue_vul_rows
overdue_vul_chart = batch_barchart(
    sheet=sheet,
    batch_size=5,
    chartType="col",
    variable="Overdue",
    x_title="Overdue",
    y_title="Count",
    min_col=2,
    max_col=overdue_vul_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell="D4",
    chartStyle=10,
    shape=4
)
overdue_vul_piechart = piechart_creation(sheet, 4, "Overdue", 2, min_row_table, max_row_table, overdue_vul_columns, False, False, False, True, "N4")
# charts_length.append(barchart_start_column_value + round(overdue_vul_chart.width / 1.7)+1+round(overdue_vul_piechart.width / 1.7))
min_row_table = min_row_table + overdue_vul_rows + 2
max_row_table = max_row_table + 2 + severity_vul_rows
severity_vul_chart = batch_barchart(
    sheet=sheet,
    batch_size=5,
    chartType="col",
    variable="Severity",
    x_title="Severity",
    y_title="Count",
    min_col=2,
    max_col=severity_vul_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell="D21",
    chartStyle=10,
    shape=4
)
severity_vul_piechart = piechart_creation(sheet, 4, "Severity", 2, min_row_table, max_row_table, severity_vul_columns, False, False, False, True, "N21")
# charts_length.append(barchart_start_column_value + round(severity_vul_chart.width / 1.7)+1+round(severity_vul_piechart.width / 1.7))
min_row_table = min_row_table + severity_vul_rows + 2
max_row_table = max_row_table + 2 + asset_group_vul_rows
asset_group_vul_chart = batch_barchart(
    sheet=sheet,
    batch_size=6,
    chartType="col",
    variable="Asset Group",
    x_title="Asset Group",
    y_title="Count",
    min_col=2,
    max_col=asset_group_vul_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell="D38",
    chartStyle=10,
    shape=4
)
asset_group_vul_piechart = piechart_creation(sheet, 4, "Asset Group", 2, min_row_table, max_row_table, asset_group_vul_columns, False, False, False, True, "N38")
# charts_length.append(barchart_start_column_value + round(asset_group_vul_chart.width / 1.7)+1+round(asset_group_vul_piechart.width / 1.7))
min_row_table = min_row_table + asset_group_vul_rows + 2
max_row_table = max_row_table + 2 + family_vul_rows
family_vul_chart = batch_barchart(
    sheet=sheet,
    batch_size=6,
    chartType="col",
    variable="Family",
    x_title="Family",
    y_title="Count",
    min_col=2,
    max_col=family_vul_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell="D55",
    chartStyle=10,
    shape=4
)
family_vul_piechart = piechart_creation(sheet, 4, "Family", 2, min_row_table, max_row_table, family_vul_columns, False, False, False, True, "N55")
# charts_length.append(barchart_start_column_value + round(family_vul_chart.width / 1.7)+1+round(family_vul_piechart.width / 1.7))

merge_cells_title(sheet, "A1", "B2", 1, 1, "Summary Table", "center", "center", "00FFFF00")
merge_cells_title(sheet, "D1", "W2", 1, 4, "Summary Table Charts", "center", "center", '0000FF00')
merge_cells_title(sheet, "A30", "B31", 30, 1, "Click here to see all variables", "center", "center", "FFCCCC")

wb.save(newfile)

### Plugin Family Sheet

In [28]:
sheet_name = "Plugin Family"
book = load_workbook(newfile, keep_vba=True)
with excel_writer(newfile) as writer:
    sheet = sheet_name
    new_row = 3
    pivot_table_1_wide.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)
    ws = writer.sheets[sheet]

    header_row = new_row+1
    first_data_row = header_row+1
    last_data_row = ws.max_row
    start_col = 1
    last_col = pivot_table_1_wide_columns

    ws.auto_filter.ref = f"{get_column_letter(start_col)}{header_row}:{get_column_letter(last_col)}{last_data_row}"

    wb = writer.book
    ws = wb[sheet]
    autosize_df_columns(ws, pivot_table_1_wide)

wb = load_workbook(newfile, keep_vba=True)
sheet = wb[sheet_name]

min_row_table = 4
max_row_table = min_row_table + pivot_table_1_wide_rows
pivot_table_1_wide_chart = batch_barchart(
    sheet=sheet,
    batch_size=5,
    chartType="col",
    variable="Severity and Plugin Family",
    x_title="Family",
    y_title="Count",
    min_col=2,
    max_col=pivot_table_1_wide_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell=f"{get_column_letter(pivot_table_1_wide_columns+3)}4",
    chartGrouping="percentStacked",
    chartOverlap=100
)

merge_cells_title(sheet, "A1", f"{get_column_letter(pivot_table_1_wide_columns)}2", 1, 1, f"{sheet_name} Table - Breakdown by Severity", "center", "center", "00FFFF00")
# merge_cells_title(sheet, f"{get_column_letter(pivot_table_1_wide_columns+3)}1", f"{get_column_letter(pivot_table_1_wide_columns+3+round(pivot_table_1_wide_chart.width / 1.7))}2", 1, pivot_table_1_wide_columns+3, "Summary Table Charts", "center", "center", '0000FF00')

wb.save(newfile)

### Asset Group Sheet

In [29]:
sheet_name = "Asset Group"
book = load_workbook(newfile, keep_vba=True)
with excel_writer(newfile) as writer:
    sheet = sheet_name
    new_row = 3
    pivot_table_2_wide.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)
    ws = writer.sheets[sheet]

    header_row = new_row+1
    first_data_row = header_row+1
    last_data_row = ws.max_row
    start_col = 1
    last_col = pivot_table_2_wide_columns

    ws.auto_filter.ref = f"{get_column_letter(start_col)}{header_row}:{get_column_letter(last_col)}{last_data_row}"
    hyperlink_cell(ws, first_data_row, last_data_row)

    wb = writer.book
    ws = wb[sheet]
    autosize_df_columns(ws, pivot_table_2_wide)

wb = load_workbook(newfile, keep_vba=True)
sheet = wb[sheet_name]

min_row_table = 4
max_row_table = min_row_table + pivot_table_2_wide_rows
pivot_table_2_wide_chart = batch_barchart(
    sheet=sheet,
    batch_size=5,
    chartType="col",
    variable="Severity and Asset Group",
    x_title="Asset Group",
    y_title="Count",
    min_col=2,
    max_col=pivot_table_2_wide_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell=f"{get_column_letter(pivot_table_2_wide_columns+3)}4",
    chartGrouping="percentStacked",
    chartOverlap=100
)

merge_cells_title(sheet, "A1", f"{get_column_letter(pivot_table_2_wide_columns)}2", 1, 1, f"{sheet_name} Table - Breakdown by Severity", "center", "center", "00FFFF00")
merge_cells_title(sheet, f"{get_column_letter(pivot_table_2_wide_columns+3)}1", "O2", 1, pivot_table_2_wide_columns+3, "Summary Table Charts", "center", "center", '0000FF00')

wb.save(newfile)

### Overdue Sheet

In [30]:
sheet_name = "Overdue"
book = load_workbook(newfile, keep_vba=True)
with excel_writer(newfile) as writer:
    sheet = sheet_name
    new_row = 3
    pivot_table_3_wide.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)
    ws = writer.sheets[sheet]

    header_row = new_row+1
    first_data_row = header_row+1
    last_data_row = ws.max_row
    start_col = 1
    last_col = pivot_table_3_wide_columns

    ws.auto_filter.ref = f"{get_column_letter(start_col)}{header_row}:{get_column_letter(last_col)}{last_data_row}"
    hyperlink_cell(ws, first_data_row, last_data_row)

    wb = writer.book
    ws = wb[sheet]
    autosize_df_columns(ws, pivot_table_3_wide)

wb = load_workbook(newfile, keep_vba=True)
sheet = wb[sheet_name]

min_row_table = 4
max_row_table = min_row_table + pivot_table_3_wide_rows
pivot_table_3_wide_chart = batch_barchart(
    sheet=sheet,
    batch_size=5,
    chartType="col",
    variable="Overdue and Plugin Family",
    x_title="Overdue",
    y_title="Count",
    min_col=2,
    max_col=pivot_table_3_wide_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell=f"{get_column_letter(pivot_table_3_wide_columns+3)}4",
    chartGrouping="percentStacked",
    chartOverlap=100
)

merge_cells_title(sheet, "A1", f"{get_column_letter(pivot_table_3_wide_columns)}2", 1, 1, f"{sheet_name} Table - Breakdown by Severity", "center", "center", "00FFFF00")
# merge_cells_title(sheet, f"{get_column_letter(pivot_table_3_wide_columns+3)}1", f"{get_column_letter(pivot_table_3_wide_columns+3+round(pivot_table_3_wide_chart.width / 1.7))}2", 1, pivot_table_3_wide_columns+3, "Summary Table Charts", "center", "center", '0000FF00')

wb.save(newfile)

### Asset Group & Family Sheet

In [31]:
sheet_name = "Asset Grp & Family"
book = load_workbook(newfile, keep_vba=True)
with excel_writer(newfile) as writer:
    sheet = sheet_name
    new_row = 3
    pivot_table_4_wide.to_excel(writer, sheet_name=sheet, startrow=new_row, startcol=0, index=False)
    ws = writer.sheets[sheet]

    header_row = new_row+1
    first_data_row = header_row+1
    last_data_row = ws.max_row
    start_col = 1
    last_col = pivot_table_4_wide_columns

    ws.auto_filter.ref = f"{get_column_letter(start_col)}{header_row}:{get_column_letter(last_col)}{last_data_row}"
    hyperlink_cell(ws, first_data_row, last_data_row, column_no=3)

    wb = writer.book
    ws = wb[sheet]
    autosize_df_columns(ws, pivot_table_4_wide)

wb = load_workbook(newfile, keep_vba=True)
sheet = wb[sheet_name]

min_row_table = 4
max_row_table = min_row_table + pivot_table_4_wide_rows
pivot_table_4_wide_chart = batch_barchart(
    sheet=sheet,
    batch_size=5,
    chartType="col",
    variable="Asset Group, Plugin Family and Severity",
    x_title="Asset Group - Plugin Family",
    y_title="Count",
    min_col=4,
    max_col=pivot_table_4_wide_columns,
    min_row=min_row_table,
    max_row=max_row_table,
    showVal=True,
    showSerName=False,
    showCatName=False,
    showLeaderLines=False,
    cell=f"{get_column_letter(pivot_table_4_wide_columns+3)}4",
    chartGrouping="percentStacked",
    chartOverlap=100
)

merge_cells_title(sheet, "A1", f"{get_column_letter(pivot_table_4_wide_columns)}2", 1, 1, f"{sheet_name} Table - Breakdown by Severity", "center", "center", "00FFFF00")
# merge_cells_title(sheet, f"{get_column_letter(pivot_table_4_wide_columns+3)}1", f"{get_column_letter(pivot_table_4_wide_columns+3+round(pivot_table_4_wide_chart.width / 1.7))}2", 1, pivot_table_4_wide_columns+3, "Summary Table Charts", "center", "center", '0000FF00')

wb.save(newfile)